### ISSUE TITLE
using D3 with Keechma

### ISSUE THREAD

**Issue by ChipNowacek** [keechma/keechma#16]
Noob question: any words of wisdom to someone looking into using D3 with Keechma?

**Comment by retro** [comment]
@ChipNowacek Using D3 with Keechma should be similar or same like using it directly with Reagent. This looks like a good [starting point](https://gadfly361.github.io/gadfly-blog/2016-10-22-d3-in-reagent.html).

Please let me know if I can help you with any problems or questions that are directly related to Keechma

**Comment by ChipNowacek** [comment]
Thank you kindly.
