### ISSUE TITLE
framework vs interface

### ISSUE THREAD

**Issue by ChipNowacek** [keechma/keechma#17]
[Clojure Toolbox](https://www.clojure-toolbox.com) lists Keechma as a React framework and OM as a React interface. For a dummy, what's the difference? Who chooses which? Any doc you could suggest?

**Comment by retro** [comment]
Keechma is built on top of [Reagent](https://github.com/reagent-project/reagent) which is listed as a React Interface. Reagent is used to write React components in Keechma apps. Keechma provides you with a structure around the app state, user interactions and routing.

Good place to start is [Reagent docs](http://reagent-project.github.io/) and [Keechma Guides](https://keechma.com/guides/)

**Comment by ChipNowacek** [comment]
Again, @retro, thank you for your generosity. I think I found the right place.
