### ISSUE TITLE
sense of history and origin

### ISSUE THREAD

**Issue by ChipNowacek** [keechma/keechma#22]
That you credit your background really helps. Bravo.

> ## Credits and Inspiration
> The libraries that had the biggest impact on Keechma:
> 
> - CanJS - Keechma's router is ported from CanJS and EntityDB is inspired by the CanJS model store
> - Re/Frame. - One-big-atom store, subscriptions and handlers are based of my experience with Re/Frame
> - Reagent - Keechma would be much harder to implement without Reagent's approach to components
> - Om - Without Om I probably wouldn't try ClojureScript, so Keechma wouldn't exist.

**Comment by ChipNowacek** [comment]
I might grow this into a "feature request". There are so many frameworks out there that it's difficult to know why anyone would decide to build another one. Understanding your thinking in creating Keechma would help those trying to make platform decisions. Here are a few questions that pop to my mind:

Big picture
- As you see it, what needs are not met by the other libraries?
- What is your vision for Keechma? That is, what do you hope Keechma will enable?
- For you personally, why Keechma's now? How does it fit in with your direction? (Answering this one in particular helps people who are wondering if Keechma will last. Project die because their creators weren't sustained by them.)

Area specific
- Why choose the CanJS db model over the `spec`-based app-db of re-frame?

Library comparisons 
- From a guy with your level of experience, when would anyone use one framework over another, including Keechma?

There are many others.

There's a way to address these types of serious questions without dishonoring the work of others — not that I can read your mind and know you have that worry.

Anyway, understanding motivations and sharing perspective makes all the difference to those overwhelmed with the details of all these tech ecosystems. And, with respect to marketing, users are drawn to those who clearly demonstrate they understand their troubles and are willing to help. In a phrase: teaching sells. If Keechma answers real problems, it's worth being sold through teaching. Rich Hickey is a fine example of this type of be-genuinely-helpful marketing.

My $0.02.

**Comment by retro** [comment]
Some of these questions are answered on my (private) blog http://retroaktive.me/blog/keechma-design-decisions/ but I do agree that they should be more prominent on the Keechma site too.

Regarding the plans for Keechma, [we](https://floatingpoint.io/) are building apps in it every day and we offer Keechma consulting and development. I will probably add a short note about it on Keechma site, but I want to avoid a situation where Keechma site is one big marketing scheme for FloatingPoint.

**Comment by ChipNowacek** [comment]
Ooohh. This helps. Thank you for explaining. Your sincerity is clear.

The fact that FloatingPoint is not only contributing the framework to the community but uses it every day to go about its business is, in my mind, a big deal — and, as you well know, I don't work for FloatingPoint. Yet I _do_ have something to gain. Understanding Keechma's origins and current use by those who built it in commercial projects helps reduce _my_ risk. I'll take every bit of risk reduction I can get. I'm _not_ alone.

Of course, it's not my place to say how you ought to represent yourself to the world. Obviously, that's your deal. As you say, overselling yourself is bad for you and everyone else. Maybe less obvious, under selling is also bad for you and everyone else. It keeps your work from those who need it. Need it. There are also those not technically able to use Keechma and need to know about your services. Just telling your story, unembellished, neither hyping or obscuring, helps people understand. Understanding is what we need to make real-life, risk-reward decisions.

The world needs good tools born of real experience. As best I can tell, that's what Keechma offers, backed by people who built it for themselves to get their own work done. That FloatingPoint gets more customers from publishing Keechma justifies all the work you do to make it available for others. I could tell you stories of really important tech that is lost to the world because people didn't go to the trouble you have to make it available.

Well, for better and worse, there is > $0.02. Now back to getting D3 working inside of Keechma. In fact, who do I talk to about your services? :)

**Comment by ChipNowacek** [comment]
The two links you sent are fabulous. The sense of story I do get is great. I wouldn't be at all surprised if you don't have to worry about more marketing at FloatingPoint because you have enough work already.

Anyway, thanks.

**Comment by retro** [comment]
@ChipNowacek You're right about the promotion. This is something I plan to tackle in the near future. I didn't work to much on promotion because I wanted to get some real life experience with Keechma before starting on that. We developed a bunch of Keechma based apps during the last year, so now it's a good time to work on the promotion.

And if you want to talk about our services feel free to directly contact me at mihael@floatingpoint.io :)
