### ISSUE TITLE
Returning 'false' from a Controller's 'params' function causes Exception

### ISSUE THREAD

**Issue by xsc** [keechma/keechma#28]
We ran into this edge case today: If the `params` function of a Controller returns `false` when the controller is started the first time, an exception is thrown [here](https://github.com/keechma/keechma/blob/master/src/keechma/controller_manager.cljs#L58):

```
Uncaught Error: No protocol method Channel.close! defined for type null:
```

Now, since `false` is not `nil`, the controller manager assumes that the controller needs to be updated. The `route-change-execution-plan`, however, [decides that this means the controller needs to be stopped, then started again](https://github.com/keechma/keechma/blob/master/src/keechma/controller_manager.cljs#L43), resulting in an attempt to close the controllers `:in-chan`, throwing the above exception.

A fix would be replacing the `boolean` calls ([here](https://github.com/keechma/keechma/blob/master/src/keechma/controller_manager.cljs#L41-L42)) with `some?`, so we end up in the correct ("start up the controller for the first time") branch.

**Comment by retro** [comment]
@xsc Thanks for reporting this, I'll try to add a test case and the fix a bit later today

**Comment by retro** [comment]
@xsc Snapshot 12 is out with the fix for this issue https://clojars.org/keechma
