### ISSUE TITLE
Time for a non-snapshot release?

### ISSUE THREAD

**Issue by priornix** [keechma/keechma#29]
Great work @retro! I am using keechma in a project, and in combination with https://github.com/keechma/keechma-toolbox (pipeline, what a great idea!) helps to structure my ClojureScript project in a good way. It may be superior to https://github.com/Day8/re-frame at the moment, but loses out in terms of developer mindshare, and buzz. I hope this project does not atrophy due to lack of developer usage.

Time for a final push to v0.3 (or a v1.0) and some marketing on Reddit / Slack / Clojure mailing list? 😉

**Comment by priornix** [comment]
Also, it would be excellent if there was a side-by-side comparison between:

* https://github.com/keechma/keechma/
* https://github.com/Day8/re-frame
* https://github.com/mpdairy/posh

It can (and should) be a tiny bit biased towards keechma.

**Comment by retro** [comment]
@priornix hey, thanks for the compliments :)

Yes, I agree that it's time for v1.0 . Keechma is actually ready, but I want to upgrade to latest ClojureScript and React / Reagent versions before pushing it out. There are some changes in React 15.5+ where they moved test utils to a different namespace, and now the cljs-react-test package should be updated so we can run the tests. But it's close.

You don't have to worry about the lack of developer usage, we at floatingpoint.io are using Keechma every day, and there's more stuff coming (related to docs and examples). But, I do agree that it seems a bit quiet over here, so I wanted to ask if you could help with that? It would be great if I could interview you for the Keechma site about your experience. I think it would be great, it would give Keechma some social proof outside the core team

Also, can you share the URL of the project that you've built?

**Comment by retro** [comment]
@priornix I'll close this issue since I've just released a non snapshot release.
