### ISSUE TITLE
ui/send-command should return nil

### ISSUE THREAD

**Issue by ingesolvoll** [keechma/keechma#7]
It's very common to have event handlers like these: `{:on-click #(ui/send-command ctx :save)}`.

It seems like that function returns false, producing warnings and possible bugs in react. Would it be a good idea to have the send-command function return nil?

**Comment by retro** [comment]
It returns whatever is the result of the `put!` function https://github.com/keechma/keechma/blob/master/src/keechma/ui_component.cljs#L50-L54 . I didn't notice any errors when using it, so can you paste me a stack trace and I'll check it.

Also in what browser is this happening?

**Comment by ingesolvoll** [comment]
I get this in chrome for event listeners that return false: 

Warning: Returning `false` from an event handler is deprecated and will be ignored in a future release. Instead, manually call e.stopPropagation() or e.preventDefault(), as appropriate.

I think reagent itself introduced some helpers for this in 0.6.0, with the `rswap!` function.

My assumption is that the majority of event handlers will be an anonymous function containing only `ui/send-command`, and having the framework helping out by returning nil will save boilerplate.

**Comment by ingesolvoll** [comment]
This isn't really a bug, but a nice way for the framework to behave, if I'm right and the return value of send-command is never used by anyone.
