### ISSUE TITLE
Supporting figwheel workflow in keechma

### ISSUE THREAD

**Issue by ingesolvoll** [keechma/keechma#9]
As you probably understood by now, I'm testing out keechma on my current app :)

One thing that I miss from my previous app is a persistent app state. Using keechma from your example, I restart the app on every recompile. When restarting, app state is wiped and loaded again, so my running state (local navigation, form input etc) is lost.

I tried NOT restarting, which blocks the code changes from kicking in.

Loving the keechma experience so far, and not wiping state on every recompile would take it a step further. Am I doing something wrong?

**Comment by retro** [comment]
@ingesolvoll I've added the `restore-app-db` function https://github.com/keechma/keechma/blob/master/src/keechma/app_state.cljs#L112-L119 .

Until the new release you can just copy it into your project and use it from the `restart-app!` function in your `main` file.

Your `restart-app!` would look something like this:

``` clojure
(defn restart-app! []
  (let [current @running-app]
    (if current
      (app-state/stop!
       current
       (fn []
         (start-app!)
         (restore-app-db current @running-app)))
      (start-app!))))
```

**Comment by ingesolvoll** [comment]
Nice :) Doesn't really help in my case though... The route being launched loads data from HTTP, overwriting the db-restore some milliseconds later. At least I assume that's what happens.

I can see that this is a bit tricky for the framework, and I'll look into potential solutions inside my app. But I would suggest a framework feature of re-bootstrapping the app without a full restart, as that would prevent a full relaunch of the routes.

Of course, sometimes you really do need a full restart of the app. But for the overall workflow, I would prefer not restarting, falling back to F5 when you really need to reset.
